export interface IChessMatchWebsocketResponse {
  type: ChessMatchWebsocketResponseEnum
}


export enum ChessMatchWebsocketResponseEnum {
  INFO = "INFO",
  SUBSCRIBED = "SUBSCRIBED",
  DISCONNECTED = "DISCONNECTED",
  CHESS_MOVE = "CHESS_MOVE",
  DRAW = "DRAW",
  REJECT_DRAW = "REJECT_DRAW",
  MATCH_RESULT = "MATCH_RESULT",
  GENERAL_BAD = "GENERAL_BAD",
  CHESS_MOVE_BAD = "CHESS_MOVE_BAD",
  DRAW_BAD = "DRAW_BAD",
  REJECT_DRAW_BAD = "REJECT_DRAW_BAD",
  ACCEPT_DRAW_BAD = "ACCEPT_DRAW_BAD",
  SURRENDER_BAD = "SURRENDER_BAD",
}
